INSERT INTO Artist VALUES ('01','Киркоров');
INSERT INTO Artist VALUES ('02','Агутин');
INSERT INTO Artist VALUES ('03','Леонтьев');
INSERT INTO Artist VALUES ('04','Долина');
INSERT INTO Artist VALUES ('05','Меладзе');
INSERT INTO Artist VALUES ('06','Варум');
INSERT INTO Artist VALUES ('07','Иванов');
INSERT INTO Artist VALUES ('08','Михайлов');
INSERT INTO Artist VALUES ('09','Стас Михайлов');
INSERT INTO Genre VALUES ('01','Rock');
INSERT INTO Genre VALUES ('02','DnB');
INSERT INTO Genre VALUES ('03','House');
INSERT INTO Genre VALUES ('04','Techno');
INSERT INTO Genre VALUES ('05','Pop');
INSERT INTO Album VALUES ('01','Nature','1985');
INSERT INTO Album VALUES ('02','Australia','2006');
INSERT INTO Album VALUES ('03','Feelings','1200');
INSERT INTO Album VALUES ('04','Rain','2020');
INSERT INTO Album VALUES ('05','Summer','2018');
INSERT INTO Album VALUES ('06','Never','1985');
INSERT INTO Album VALUES ('07','Emotions','2000');
INSERT INTO Album VALUES ('08','New York','2001');
INSERT INTO Track VALUES ('01','Never know','10','01');
INSERT INTO Track VALUES ('02','You know this better','10','02');
INSERT INTO Track VALUES ('03','Neighbourhood','10','03');
INSERT INTO Track VALUES ('04','Village','10','04');
INSERT INTO Track VALUES ('05','River','10','05');
INSERT INTO Track VALUES ('06','The End','10','06');
INSERT INTO Track VALUES ('07','Rainbow','10','07');
INSERT INTO Track VALUES ('08','Barrel','10','08');
INSERT INTO Track VALUES ('09','How much is the cost','10','01');
INSERT INTO Track VALUES ('10','Poison','10','02');
INSERT INTO Track VALUES ('11','Milky way','10','03');
INSERT INTO Track VALUES ('12','Starship','10','04');
INSERT INTO Track VALUES ('13','Friendship','10','05');
INSERT INTO Track VALUES ('14','Love','10','06');
INSERT INTO Track VALUES ('15','Like movie','10','07');
INSERT INTO Track VALUES ('16','My world','10','07');
INSERT INTO Track VALUES ('17','Its my life','11','08');
INSERT INTO Track VALUES ('18','Its my work','5','08');
INSERT INTO Track VALUES ('19','Jungle','1','06');
INSERT INTO Track VALUES ('20','Star','3','01');
INSERT INTO Track VALUES ('21','Fish','2','03');
INSERT INTO Track VALUES ('22','Door','1.5','07');
INSERT INTO Track VALUES ('23','Wind','3.5','02');
INSERT INTO Track VALUES ('24','Water','2.5','05');
INSERT INTO Collection VALUES ('01','Romantic','1986');
INSERT INTO Collection VALUES ('02','Energetic','2007');
INSERT INTO Collection VALUES ('03','Positive','1201');
INSERT INTO Collection VALUES ('04','Relaxing','2022');
INSERT INTO Collection VALUES ('05','All in one','2019');
INSERT INTO Collection VALUES ('06','Only POP','1986');
INSERT INTO Collection VALUES ('07','Best Tracks','1999');
INSERT INTO Collection VALUES ('08','80s','2002');
INSERT INTO Collection VALUES ('09','Best 90s','2018');
INSERT INTO Collection VALUES ('10','Lounge','2020');
INSERT INTO TrackCollection VALUES ('01','04');
INSERT INTO TrackCollection VALUES ('02','02');
INSERT INTO TrackCollection VALUES ('03','02');
INSERT INTO TrackCollection VALUES ('04','07');
INSERT INTO TrackCollection VALUES ('05','06');
INSERT INTO TrackCollection VALUES ('06','08');
INSERT INTO TrackCollection VALUES ('07','01');
INSERT INTO TrackCollection VALUES ('08','01');
INSERT INTO TrackCollection VALUES ('09','02');
INSERT INTO TrackCollection VALUES ('10','03');
INSERT INTO TrackCollection VALUES ('11','04');
INSERT INTO TrackCollection VALUES ('12','05');
INSERT INTO TrackCollection VALUES ('13','06');
INSERT INTO TrackCollection VALUES ('14','07');
INSERT INTO TrackCollection VALUES ('15','08');
INSERT INTO AlbumArtist VALUES ('01','08');
INSERT INTO AlbumArtist VALUES ('02','07');
INSERT INTO AlbumArtist VALUES ('03','06');
INSERT INTO AlbumArtist VALUES ('04','05');
INSERT INTO AlbumArtist VALUES ('05','04');
INSERT INTO AlbumArtist VALUES ('06','03');
INSERT INTO AlbumArtist VALUES ('07','02');
INSERT INTO AlbumArtist VALUES ('08','01');
INSERT INTO GenreArtist VALUES ('01','03');
INSERT INTO GenreArtist VALUES ('02','02');
INSERT INTO GenreArtist VALUES ('03','01');
INSERT INTO GenreArtist VALUES ('04','05');
INSERT INTO GenreArtist VALUES ('05','04');
INSERT INTO GenreArtist VALUES ('01','03');
INSERT INTO GenreArtist VALUES ('02','02');
INSERT INTO GenreArtist VALUES ('03','01');